server:
  port: 9092
spring:
  application:
    name: config-client
management:
  endpoints:
    web:
      exposure:
        #开启全部端点
        include: "*"
  endpoint:
    health:
      #详细信息
      show-details: always
