
server.port: 8082
spring:
  application:
    name: gateway


logging:
  level:
    #org.springframework.cloud.gateway: debug
    cn.springcloud.book.filter: debug


#¿ªÆô¶Ëµã
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
