server:
  port: 8081
spring:
  application:
    name: eureka-client1

eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 90 #指定Client 向Server 多久之后发送心跳告知 还存活 默认90 秒
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/