spring:
  application:
    name: client-a

eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      host-mark: gray
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7072