
server:
  port: 9020
spring:
  application:
    name: config-apollo-client_new
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
apollo:
  bootstrap:
    enabled: true
    namespace: application
  meta: http://192.168.42.128:8080